name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install
    - run: npm run build --if-present
    - name: upload to tencentcloud
      uses: TencentCloudBase/cloudbase-action@v1
      with:
          secretId: ${{ secrets.secretId }}
          secretKey: ${{ secrets.secretKey }}
          envId: ${{ secrets.envId }}
          staticSrcPath: dist
    - name: Get the deploy result
      run: echo "Deploy to cloudbase result ${{ steps.deployStatic.outputs.deployResult }}"
    - run: echo "Done"
